version: '3'

services:
  frontend:
    build:
      context: ./front/bank-expert-system
    ports:
      - "8080:8080"
    image: tshepak/bank-expert-system:inittagfrontend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    image: tshepak/bank-expert-system:inittag
